version: "3.8"
services:
  app:
    container_name: spring-boot-app
    build:
      dockerfile: Dockerfile
    image: spring-boot-app
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/book_details_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - spring-mysql-network
  mysqldb:
    image: mysql:8.0.38
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_details_db
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    networks:
      - spring-mysql-network
volumes:
  my-db:
networks:
  spring-mysql-network: