version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/book_details_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - springmysql

  db:
    image: mysql:8.0.38
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_details_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - springmysql

networks:
  springmysql:
    driver: bridge